[project]
name = "proj1"
version = "0.1.0"
description = "Recycling Robot Reinforcement Learning with Temporal Difference Learning"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "seaborn>=0.13.2",
]
